Add `stripeCustomerId` Parameter to Organization Methods
workos/workos-php pull request #250
Opened 2024-12-05 03:44 UTC by Hannes-Kruger

## Description

This pull request introduces support for the `stripeCustomerId` parameter in the PHP SDK's `updateOrganization` method. This aligns the SDK with WorkOS's existing API functionality, enabling developers to specify a Stripe Customer ID when updating an organization.

### Changes in this PR:
1. **`updateOrganization` Method:**
   - Added a new optional parameter: `$stripeCustomerId`.
   - Includes the `stripe_customer_id` field in the request payload when provided.

These changes do not affect existing behavior and remain fully backward-compatible.

### Code Diff
Relevant code snippets for the additions:
```php
if (isset($stripeCustomerId)) {
    $params["stripe_customer_id"] = $stripeCustomerId;
}
```

## Documentation

Does this require changes to the WorkOS Docs? E.g., the [API Reference](https://workos.com/docs/reference) or code snippets need updates.

[ ] Yes  
[X] No

This update reflects an existing API feature, so no changes to the WorkOS documentation are required.

### Testing

No tests have been added for this change. The implementation follows the existing structure for handling optional parameters, and the changes have been manually verified to ensure they align with the expected behavior.

### Backward Compatibility:

- Verified that omitting the stripeCustomerId parameter does not affect the current behavior of the methods.

### Additional Notes

This update ensures parity with WorkOS's API functionality, enabling seamless integration of Stripe Entitlements for organizations. Future updates could include test coverage for this parameter.

2024-12-05 09:33 UTC, PaulAsjes requested changes
Thanks for this! 

While `updateOrganization` definitely needs the optional `stripeCustomerId` parameter, `createOrganization` doesn't accept a Stripe customer ID presently: https://workos.com/docs/reference/organization/create

I think we should consider adding the Stripe customer ID when creating an organization, but for this PR would you mind removing that part?

2024-12-05 21:03 UTC, Hannes-Kruger commented
Ah ok, I missed that! I'll make the change

2024-12-05 21:06 UTC, Hannes-Kruger commented
Done

2024-12-06 08:34 UTC, PaulAsjes approved these changes
Thanks so much!

2024-12-06 08:35 UTC, merged